### PR TITLE
Python 3.5 and TensorFlow 0.12 ready

### PR DESCRIPTION
**Pull request by ziemowit-s**
Adjusted code for Python 3.5 and TensorFlow 0.12

### CODE REVIEW

**Comment by jhlau** [comment]
Hmm is the code properly tested? I can create a python3.5 branch for this.

**Comment by ziemowit-s** [comment]
I can't say it've been 100% tested. I used it in tag/target/unsupervised training/test. Also checked most of parameters from readme, so if you find it helpful for the python3.5 branch - good, if not - that's fine :)

**Comment by jhlau** [comment]
Okay. Can I ask you to resubmit the pull request to a python3.5 branch? I can manually merge it into a branch but it's cleaner if you submit the PR to a new branch.

**Comment by jhlau** [comment]
Alright I've gone ahead and merged the PR into a python3 branch. Closing thread.

**Comment by ziemowit-s** [comment]
Sorry I haven't log on Github during the weekend

**Pull request closed without merging**
